bf16: true
cutoff_len: 8192
dataset: My_data
dataset_dir: data
ddp_timeout: 180000000
deepspeed: ds_z2_offload_config.json
do_train: true
enable_thinking: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /mnt/nvme1n1/wjc/Model/Qwen3-8B-merged
num_train_epochs: 2.0
optim: adamw_torch
output_dir: saves/Qwen3-8B-Instruct/lora/train
packing: false
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
swanlab_api_key: 
swanlab_mode: cloud
swanlab_project: Qwen3-8B
swanlab_run_name: Qwen3-8B-merged
template: qwen3
trust_remote_code: true
use_swanlab: true
warmup_steps: 0
